x-environment:
  &QUICKSTART_ENVIRONMENT
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  PLAID_ENV: ${PLAID_ENV}

services:
  node:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./node/Dockerfile
    ports: ["8001:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT

  frontend:
    environment:
      - REACT_APP_API_HOST=http://node:8000
    networks:
      - "quickstart"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports: ["3002:3000"]

networks:
  quickstart:
    name: quickstart
